//! The clock floor: the running system is never older than the image it is running.
//!
//! An appliance with a dead CMOS battery boots believing it is 1970. Every certificate
//! on the internet is then "not yet valid", so provisioning Plex fails, checking for an
//! update fails, and both fail with a message about a *certificate* — which is where
//! anybody reading it will look, and it is not where the fault is.
//!
//! There is no NTP in this image and adding one would not fix this anyway: the first
//! thing a time client needs is a network, and by the time the network is up the console
//! has already tried to speak TLS.
//!
//! # The rule
//!
//! **A system cannot be running from an image that had not been built yet.** The image
//! stamps its own build minute into `VERSION_ID` — `0.1.0.202608092053` — and that string
//! is inside the dm-verity `/usr` this boot just mounted, so it is as trustworthy as the
//! root hash makes everything else. If the clock reads earlier than that, it is wrong by
//! proof rather than by guess, and the build time is a better answer than the one the
//! hardware gave.
//!
//! This is what systemd calls its epoch, for the same reason and by the same argument.
//!
//! # What it does not claim
//!
//! It does not set the *correct* time, and nothing here pretends otherwise. A machine
//! that has been off for a month comes back believing it is the day the image was built.
//! What that buys is a clock that is never absurd, so TLS works and file timestamps sort
//! in the right order; and every update moves the floor forward. Getting the actual time
//! needs a time source, which is a separate decision.
//!
//! The clock is never moved *backwards*. A machine whose battery is fine keeps the time
//! it had, and an image installed today onto a machine that has been running for a week
//! does not lose that week.

/// Reads one `KEY=value` out of os-release contents.
///
/// Values may be quoted, and Buildroot writes some of them that way. Anything that is
/// not a bare `KEY=` line is skipped rather than parsed loosely, because the caller of
/// this decides what the system clock becomes.
#[must_use]
pub fn os_release_value<'a>(contents: &'a str, key: &str) -> Option<&'a str> {
    contents.lines().find_map(|line| {
        let (name, value) = line.split_once('=')?;
        if name.trim() != key {
            return None;
        }
        Some(value.trim().trim_matches('"'))
    })
}

/// Turns `0.1.0.202608092053` into seconds since the epoch.
///
/// The build stamp is the fourth dotted component and is exactly `YYYYMMDDHHMM`. A
/// version without one — `0.1.0`, which is what a build with no `PLEXOS_VERSION` used to
/// produce — yields `None`, and the caller then leaves the clock alone. Refusing to guess
/// matters more here than covering that case: the alternative to an unknown floor is no
/// floor, not an invented one.
#[must_use]
pub fn build_time(version_id: &str) -> Option<i64> {
    let stamp = version_id.split('.').nth(3)?;
    if stamp.len() != 12 || !stamp.bytes().all(|b| b.is_ascii_digit()) {
        return None;
    }

    let number = |from: usize, to: usize| stamp[from..to].parse::<i64>().ok();
    let (year, month, day) = (number(0, 4)?, number(4, 6)?, number(6, 8)?);
    let (hour, minute) = (number(8, 10)?, number(10, 12)?);

    // A stamp is generated by `date -u`, so these hold unless the string was hand-written.
    // Checked anyway: a malformed one that parsed would set the clock to something absurd
    // and be much harder to recognise afterwards than a refusal here.
    if !(1..=12).contains(&month)
        || !(1..=31).contains(&day)
        || !(0..=23).contains(&hour)
        || !(0..=59).contains(&minute)
    {
        return None;
    }

    Some(days_from_civil(year, month, day) * 86_400 + hour * 3_600 + minute * 60)
}

/// Days since 1970-01-01 for a proleptic Gregorian date.
///
/// Howard Hinnant's `days_from_civil`, which is exact for every year this will ever see
/// and needs no table. Written out rather than pulled in as a dependency: PID 1 is the
/// process where a crate that panics is a machine that does not boot.
fn days_from_civil(year: i64, month: i64, day: i64) -> i64 {
    let year = if month <= 2 { year - 1 } else { year };
    let era = if year >= 0 { year } else { year - 399 } / 400;
    let year_of_era = year - era * 400;
    let day_of_year = (153 * (if month > 2 { month - 3 } else { month + 9 }) + 2) / 5 + day - 1;
    let day_of_era = year_of_era * 365 + year_of_era / 4 - year_of_era / 100 + day_of_year;
    era * 146_097 + day_of_era - 719_468
}

/// What the clock should become, or `None` to leave it alone.
///
/// Separate from anything that reads a file or issues a syscall so that the decision — the
/// part that can be wrong in a way nobody notices for months — is testable on its own.
#[must_use]
pub fn correction(now: i64, floor: i64) -> Option<i64> {
    (now < floor).then_some(floor)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_build_stamp_becomes_the_moment_it_names() {
        // Pinned against a value computed by something outside this crate, which is the
        // rule for any constant that comes from elsewhere. `date -u -d '2026-08-09
        // 20:53:00' +%s` gives 1786308780. If this fails, the arithmetic below is what
        // changes, not the number.
        assert_eq!(build_time("0.1.0.202608092053"), Some(1_786_308_780));
    }

    #[test]
    fn the_leap_year_rule_that_is_usually_wrong_is_right() {
        // 2000 is a leap year and 1900 is not, which is the case a naive `% 4` gets
        // wrong. `date -u -d '2000-03-01' +%s` gives 951868800 — the day after the
        // 29th of February that has to exist for this to line up.
        assert_eq!(build_time("0.1.0.200003010000"), Some(951_868_800));
    }

    #[test]
    fn the_epoch_itself_round_trips() {
        assert_eq!(build_time("0.1.0.197001010000"), Some(0));
    }

    #[test]
    fn a_version_without_a_stamp_leaves_the_clock_alone() {
        // What a build with no PLEXOS_VERSION produces. There is no floor to apply, and
        // inventing one would be worse than having none.
        assert_eq!(build_time("0.1.0"), None);
        assert_eq!(build_time(""), None);
    }

    #[test]
    fn a_malformed_stamp_is_refused_rather_than_coerced() {
        assert_eq!(build_time("0.1.0.20260809205"), None, "eleven digits");
        assert_eq!(build_time("0.1.0.2026080920530"), None, "thirteen digits");
        assert_eq!(build_time("0.1.0.20261309205300"), None, "too long");
        assert_eq!(build_time("0.1.0.202613092053"), None, "month 13");
        assert_eq!(build_time("0.1.0.202600092053"), None, "month 0");
        assert_eq!(build_time("0.1.0.202608092453"), None, "hour 24");
        assert_eq!(build_time("0.1.0.20260809zz53"), None, "not digits");
    }

    #[test]
    fn the_clock_is_raised_only_when_it_is_behind() {
        assert_eq!(correction(100, 200), Some(200), "behind the floor");
        assert_eq!(correction(200, 200), None, "exactly at it");
        assert_eq!(correction(300, 200), None, "ahead of it");
    }

    #[test]
    fn a_clock_stuck_at_the_epoch_is_the_case_this_exists_for() {
        let floor = build_time("0.1.0.202608092053").expect("a well-formed stamp");
        assert_eq!(correction(0, floor), Some(floor));
    }

    #[test]
    fn a_machine_that_has_been_running_does_not_lose_that_time() {
        // The regression that would matter most: an update installed onto a machine with
        // a working clock must not drag it back to the build minute.
        let floor = build_time("0.1.0.202608092053").expect("a well-formed stamp");
        assert_eq!(correction(floor + 604_800, floor), None, "a week later");
    }

    #[test]
    fn version_id_is_read_quoted_or_bare() {
        assert_eq!(
            os_release_value(
                "NAME=\"MediaLith\"\nVERSION_ID=0.1.0.202608092053\n",
                "VERSION_ID"
            ),
            Some("0.1.0.202608092053")
        );
        assert_eq!(
            os_release_value("VERSION_ID=\"0.1.0.202608092053\"\n", "VERSION_ID"),
            Some("0.1.0.202608092053")
        );
        assert_eq!(os_release_value("NAME=MediaLith\n", "VERSION_ID"), None);
    }
}
